version : '3'
services :
  server :
    build : ./server
    ports :
      - "8082:8080"
    volumes :
      - ./server:/app/server
    networks :
      - server_network
    stdin_open : true
    tty : true

networks :
  server_network :
    driver : bridge


